a## Basic of Python

# DATATYPE

In [ ]:
x = 50
print(x)
x = 60.5
print(x)
x = "Hello World"
print(x)
x = ["geeks", "for", "geeks"]
print(x)
x = ("geeks", "for", "geeks")
print(x)


50
60.5
Hello World
['geeks', 'for', 'geeks']
('geeks', 'for', 'geeks')


Numeric Data Types

In [ ]:
a = 5
b = 5.0
c = 2 + 4j

print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'complex'>


In [ ]:
s = 'Welcome to the Geeks World'
print(s)
print(type(s))

# access string with index
print(s[1])
print(s[-1])

Welcome to the Geeks World
<class 'str'>
e
d


# Sequence Data Types
1. String

2. List

In [ ]:
a = [1, 2, 3]
print(a)

b = ["Geeks", "For", "Geeks", 4, 5]
print(b[3])
print(b[-3])

[1, 2, 3]
4
Geeks


3. Tuple

In [ ]:
t1 = (1,)
print(type(t1))

t2 = ('Geeks', 'For', 'Geeks', 1, 2)
print(t2[3])
print(t2[-3])

<class 'tuple'>
1
Geeks


Set Data Type

Sets are unordered and mutable collections used to store unique elements. Since sets are unordered, elements cannot be accessed using indexing. Elements are usually accessed by iterating through the set using a loop.

In [ ]:
s1 = {"a", "a", "b", "c", "b"}
print(s1)

s2 = {"Geeks", "For", "Geeks"}
for i in s2:
    print(i)

{'c', 'b', 'a'}
Geeks
For


Dictionary Data Type

In [ ]:
d = {1: 'Geeks', 2: 'For', 3: 'Geeks'}
print(d[1])
print(d.get(2))

Geeks
For


## If Statement

In [ ]:
age = 20
if age >= 18:
    print("Eligible to vote.")

Short Hand if

In [ ]:
age = 19
if age > 18: print("Eligible to Vote.")

Eligible to Vote.


If else Statement

In [ ]:
age = 10
if age <= 12:
    print("Travel for free.")
else:
    print("Pay for ticket.")

Travel for free.


If-elif-else Statement

In [ ]:
age = 25

if age <= 12:
    print("Child.")
elif age <= 19:
    print("Teenager.")
elif age <= 35:
    print("Young adult.")
else:
    print("Adult.")

Young adult.


Nested if-else Statement

In [ ]:
age = 70
is_member = True

if age >= 60:
    if is_member:
        print("30% senior discount!")
    else:
        print("20% senior discount.")
else:
    print("Not eligible for a senior discount.")

30% senior discount!


Match-Case Statement

In [ ]:
number = 2

match number:
    case 1:
        print("One")
    case 2 | 3:
        print("Two or Three")
    case _:
        print("Other number")

Two or Three


For Loop

In [ ]:
n = 4
for i in range(0, n):
    print(i)

0
1
2
3


Iterating by Index of Sequences

In [ ]:
a = ["geeks", "for", "geeks"]
for idx in range(len(a)):
    print(a[idx])

geeks
for
geeks


While Loop

In [ ]:
cnt = 0
while (cnt < 3):
    cnt = cnt + 1
    print("Hello Geek")

Hello Geek
Hello Geek
Hello Geek


Infinite While Loop

In [ ]:
while (True):
    print("Hello Geek")

Streaming output truncated to the last 5000 lines.
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hel

KeyboardInterrupt: 

Nested Loops

In [ ]:
for i in range(1, 5):
    for j in range(i):
        print(i, end=' ')
    print()

1 
2 2 
3 3 3 
4 4 4 4 


Python Functions

In [ ]:
def fun():
    print("Welcome to GFG")

In [ ]:
def fun():
    print("Welcome to GFG")

fun()

Welcome to GFG


In [ ]:
def evenOdd(x):
    if (x % 2 == 0):
        return "Even"
    else:
        return "Odd"

print(evenOdd(16))
print(evenOdd(7))

Even
Odd


Return Statement

In [ ]:
def sq_value(num):
    return num**2

print(sq_value(2))
print(sq_value(-4))

4
16


Pass by Reference and Pass by Value

In [ ]:
def myFun(x):
    x[0] = 20

b = [10, 11, 12, 13]
myFun(b)
print(b)

def myFun2(x):
    x = 20

a = 10
myFun2(a)
print(a)

[20, 11, 12, 13]
10


Python NumPy

A NumPy array (ndarray) is a collection of elements of the same data type stored in a multidimensional structure. Arrays provide an efficient way to store and perform operations on numerical data.

Number of dimensions in an array is called its rank.
Size of the array along each dimension is called its shape.
Elements are accessed using square brackets [] and arrays are commonly created from Python lists.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

arr = np.array((1, 3, 2))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


Explanation:

np.array([1, 2, 3]) creates a one-dimensional array from a list.

np.array([[1, 2, 3], [4, 5, 6]]) creates a two-dimensional array from a nested list.

np.array((1, 3, 2)) creates a one-dimensional array from a tuple.

Accessing the Array Index

Elements in a NumPy array can be accessed using indexing and slicing. Indexing retrieves specific elements, while slicing extracts a range of elements from an array.

In [ ]:
import numpy as np

arr = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])

arr2 = arr[:2, ::2]
print("First 2 rows and alternate columns:\n", arr2)

arr3 = arr[[1, 1, 0, 3], [3, 2, 1, 0]]
print("Selected elements:", arr3)

First 2 rows and alternate columns:
 [[-1.  0.]
 [ 4.  6.]]
Selected elements: [0. 6. 2. 3.]


Basic Array Operations

In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[4, 3],
              [2, 1]])

print("Adding 1 to every element:\n", a + 1)
print("Subtracting 2 from each element:\n", b - 2)
print("Sum of all array elements:", a.sum())
print("Array sum:\n", a + b)

Adding 1 to every element:
 [[2 3]
 [4 5]]
Subtracting 2 from each element:
 [[ 2  1]
 [ 0 -1]]
Sum of all array elements: 10
Array sum:
 [[5 5]
 [5 5]]


Data Types in Numpy

In [ ]:
import numpy as np

x = np.array([1, 2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1, 2], dtype = np.int64)
print(x.dtype)

int64
float64
int64


Pandas Step by Step Guide

In [ ]:
import pandas as pd

data = {
    'Name': ["Player_A", "Player_B", "Player_C"],
    'Age': [25, 30, 35]}

df = pd.DataFrame(data)

print(df)

       Name  Age
0  Player_A   25
1  Player_B   30
2  Player_C   35


3. Creating Series

In [ ]:
import pandas as pd
age_series = pd.Series([25, 30, 35], index=["Player_A", "Player_B", "Player_C"])
print(age_series)

Player_A    25
Player_B    30
Player_C    35
dtype: int64


Reading CSV

In [ ]:
import pandas as pd
df = pd.read_csv("people.csv")
print(df)

In [ ]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'Age': [24, 27, 22, 32, 29],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']}
df = pd.DataFrame(data)

print("First 3 rows using head():")
print(df.head(3))

print("\nLast 2 rows using tail():")
print(df.tail(2))

print("\nDataFrame summary using info():")
df.info()

First 3 rows using head():
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

Last 2 rows using tail():
    Name  Age     City
3  David   32  Houston
4    Eva   29  Phoenix

DataFrame summary using info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes


Handling Missing Data in Pandas

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'Col1': [1, 2, np.nan],'Col2': [3, np.nan, np.nan]})

print(df.isnull())

    Col1   Col2
0  False  False
1  False   True
2   True   True


Filling Missing Data

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'Col1': [1, 2, np.nan],'Col2': [3, np.nan, np.nan]})
df.fillna(0,inplace=True)

print(df)

   Col1  Col2
0   1.0   3.0
1   2.0   0.0
2   0.0   0.0


Dropping Missing Data With Pandas

In [ ]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', None], 'Age': [25, None, 35]}
df = pd.DataFrame(data)
df_dropped = df.dropna()

print(df_dropped)

    Name   Age
0  Alice  25.0


Aggregation and Grouping With Pandas

In [ ]:
import pandas as pd

data = {'Category': ['A', 'B', 'A', 'B'], 'Value': [10, 20, 30, 40]}
df = pd.DataFrame(data)

grouped_sum = df.groupby('Category').sum()
print("Sum:\n", grouped_sum)

grouped_mean = df.groupby('Category')['Value'].mean()
print("\nMean:\n", grouped_mean)

grouped_agg = df.groupby('Category').agg(['sum', 'mean'])
print("\nAggregated:\n", grouped_agg)

Sum:
           Value
Category       
A            40
B            60

Mean:
 Category
A    20.0
B    30.0
Name: Value, dtype: float64

Aggregated:
          Value      
           sum  mean
Category            
A           40  20.0
B           60  30.0


Merging and Concatenating Data in Pandas

In [ ]:
import pandas as pd

data1 = {
    'Name': ['Alice', 'Charlie', 'Edward', 'Grace'],
    'Years_Experience': [2, 3, 4, 6]
}
df1 = pd.DataFrame(data1)

data2 = {
    'Name': ['Alice', 'Charlie', 'Frank', 'Grace'],
    'Role': ['Manager', 'Analyst', 'Developer', 'HR']
}
df3 = pd.DataFrame(data2)

df_merged_inner = pd.merge(df1, df3, on='Name', how='inner')

df_merged_outer = pd.merge(df1, df3, on='Name', how='outer')

print("\nInner Merge (Intersection of Names):\n", df_merged_inner)
print("\nOuter Merge (Union of Names):\n", df_merged_outer)


Inner Merge (Intersection of Names):
       Name  Years_Experience     Role
0    Alice                 2  Manager
1  Charlie                 3  Analyst
2    Grace                 6       HR

Outer Merge (Union of Names):
       Name  Years_Experience       Role
0    Alice               2.0    Manager
1  Charlie               3.0    Analyst
2   Edward               4.0        NaN
3    Frank               NaN  Developer
4    Grace               6.0         HR


Concatenating Data

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Charlie', 'Edward', 'Grace'],
    'Years_Experience': [2, 3, 4, 6],
    'Role': ['Manager', 'Analyst', 'Developer', 'HR']
})


new_df = pd.DataFrame({
    'Name': ['John', 'Lily'],
    'Years_Experience': [5, 3],
    'Role': ['Designer', 'Developer']
})


concatenated_df = pd.concat([df, new_df], ignore_index=True)

print("Concatenated DataFrame:\n")
print(concatenated_df)

Concatenated DataFrame:

      Name  Years_Experience       Role
0    Alice                 2    Manager
1  Charlie                 3    Analyst
2   Edward                 4  Developer
3    Grace                 6         HR
4     John                 5   Designer
5     Lily                 3  Developer


Reshaping Data in Pandas

In [ ]:
import pandas as pd

data = {'Date': ['2024-10-01', '2024-10-01', '2024-10-02', '2024-10-02'],'Category': ['A', 'B', 'A', 'B'],'Values': [10, 20, 15, 25]}
df = pd.DataFrame(data)

pivot_table = df.pivot_table(values='Values', index='Date', columns='Category', aggfunc='sum')
print(pivot_table)

Category     A   B
Date              
2024-10-01  10  20
2024-10-02  15  25
